function apply_axes(ax, theme)
%APPLY_AXES 应用克制的论文坐标轴样式，不覆盖数据语义设置。

set(ax, ...
    'FontName', theme.font_name, ...
    'FontSize', theme.font_size, ...
    'LineWidth', theme.axis_line_width, ...
    'TickDir', 'out', ...
    'TickLength', [0.018, 0.018], ...
    'Box', 'off', ...
    'Layer', 'top', ...
    'XColor', theme.colors.black, ...
    'YColor', theme.colors.black, ...
    'GridColor', theme.colors.gray, ...
    'GridAlpha', 0.16, ...
    'MinorGridAlpha', 0.08);
grid(ax, 'on');
end
