function handle = direct_label(ax, x, y, label, color, offset)
%DIRECT_LABEL 在关键点附近直接写结论，减少图例和视线往返。

if nargin < 5 || isempty(color), color = [0.15, 0.15, 0.15]; end
if nargin < 6 || isempty(offset), offset = [6, 0]; end
handle = text(ax, x, y, label, ...
    'Color', color, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'middle', ...
    'Units', 'data');
handle.Position(1) = handle.Position(1) + offset(1) * diff(ax.XLim) / 100;
handle.Position(2) = handle.Position(2) + offset(2) * diff(ax.YLim) / 100;
end
