function [fig, theme] = paper_figure(widthCm, heightCm)
%PAPER_FIGURE 创建与 CUMCM 正文页宽匹配的无界面论文图。

if nargin < 1 || isempty(widthCm), widthCm = 17.6; end
if nargin < 2 || isempty(heightCm), heightCm = 11.2; end
assert(widthCm >= 8 && widthCm <= 20, 'Figure width must be 8--20 cm');
assert(heightCm >= 5 && heightCm <= 24, 'Figure height must be 5--24 cm');

theme = struct();
theme.font_name = 'Microsoft YaHei';
theme.font_size = 9.0;
theme.title_size = 10.0;
theme.line_width = 1.45;
theme.axis_line_width = 0.75;
theme.marker_size = 6.5;
theme.colors = shumoviz.palette();

% 固定物理尺寸，使屏幕预览和论文内实际字号保持一致。
fig = figure( ...
    'Color', 'w', ...
    'Units', 'centimeters', ...
    'Position', [2, 2, widthCm, heightCm], ...
    'PaperPositionMode', 'auto', ...
    'Renderer', 'painters', ...
    'Visible', 'off');
set(fig, ...
    'DefaultAxesFontName', theme.font_name, ...
    'DefaultAxesFontSize', theme.font_size, ...
    'DefaultTextFontName', theme.font_name, ...
    'DefaultTextFontSize', theme.font_size, ...
    'DefaultLineLineWidth', theme.line_width, ...
    'DefaultLegendFontName', theme.font_name, ...
    'DefaultLegendFontSize', theme.font_size);
end
